CREATE SEQUENCE SEQ_UPC_MATRICULA MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE UPC_ALUMNO (
  ALUMNOID NUMBER PRIMARY KEY,
  NUMERODOCUMENTOIDENTIDAD VARCHAR2(8),
  CODIGO VARCHAR2(10),
  NOMBRES VARCHAR2(100),
  APELLIDOS VARCHAR2(100),
  ESTADO NUMBER(1)
);

CREATE TABLE UPC_CURSO (
  CURSOID NUMBER PRIMARY KEY,
  DESCRIPCION VARCHAR2(100),
  CANTIDADCREDITOS INTEGER,
  ESTADO NUMBER(1)
);

CREATE TABLE UPC_SECCION (
  SECCIONID NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(100),
  ESTADO NUMBER(1)
);

CREATE TABLE UPC_SECCIONCURSO (
  SECCIONID NUMBER,
  CURSOID NUMBER,
  CANTIDADVACANTES NUMBER,
  CANTIDADVACANTESDISPONIBLES NUMBER,
  CANTIDADVACANTESUSADAS NUMBER,
  PRIMARY KEY (SECCIONID, CURSOID)
);

CREATE TABLE UPC_TIPOMATRICULA (
  TIPOMATRICULAID NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(20)
);

CREATE TABLE UPC_MATRICULA (
  MATRICULAID NUMBER PRIMARY KEY,
  SECCIONID NUMBER,
  CURSOID NUMBER,
  ALUMNOID NUMBER,
  TIPOMATRICULAID NUMBER,
  FECHAMATRICULA TIMESTAMP,
  FLAGANULADO NUMBER(1),
  FECHAANULADO TIMESTAMP
);

INSERT INTO UPC_ALUMNO (ALUMNOID, NUMERODOCUMENTOIDENTIDAD, CODIGO, NOMBRES, APELLIDOS, ESTADO)
SELECT A.ALUMNOID, A.NUMERODOCUMENTOIDENTIDAD, A.CODIGO, A.NOMBRES, A.APELLIDOS, A.ESTADO
FROM
(
  SELECT 1 ALUMNOID, '71706762' NUMERODOCUMENTOIDENTIDAD, 'UPC0000001' CODIGO, 'JIMENA SANDY' NOMBRES, 'TAPULLIMA FASABI' APELLIDOS, 1 ESTADO FROM DUAL UNION ALL
  SELECT 2 ALUMNOID, '30675889' NUMERODOCUMENTOIDENTIDAD, 'UPC0000002' CODIGO, 'DINA BACILIA' NOMBRES, 'ZEGARRA CHIPANA' APELLIDOS, 1 ESTADO FROM DUAL UNION ALL
  SELECT 3 ALUMNOID, '30493087' NUMERODOCUMENTOIDENTIDAD, 'UPC0000003' CODIGO, 'RAIDA DEIDAMIA' NOMBRES, 'CADENAS HUAMANI' APELLIDOS, 1 ESTADO FROM DUAL UNION ALL
  SELECT 4 ALUMNOID, '45027450' NUMERODOCUMENTOIDENTIDAD, 'UPC0000004' CODIGO, 'CAROLINA' NOMBRES, 'REYES CRUZ' APELLIDOS, 1 ESTADO FROM DUAL UNION ALL
  SELECT 5 ALUMNOID, '22724246' NUMERODOCUMENTOIDENTIDAD, 'UPC0000005' CODIGO, 'POMPILIO' NOMBRES, 'JUSTO DURAN' APELLIDOS, 1 ESTADO FROM DUAL
) A;

INSERT INTO UPC_CURSO (CURSOID, DESCRIPCION, CANTIDADCREDITOS, ESTADO)
SELECT CURSOID, DESCRIPCION, CANTIDADCREDITOS, ESTADO
FROM
(
  SELECT 1 CURSOID, 'CURSO 1' DESCRIPCION, 2 CANTIDADCREDITOS, 1 ESTADO FROM DUAL UNION ALL
  SELECT 2 CURSOID, 'CURSO 2' DESCRIPCION, 2 CANTIDADCREDITOS, 1 ESTADO FROM DUAL UNION ALL
  SELECT 3 CURSOID, 'CURSO 3' DESCRIPCION, 3 CANTIDADCREDITOS, 1 ESTADO FROM DUAL UNION ALL
  SELECT 4 CURSOID, 'CURSO 4' DESCRIPCION, 5 CANTIDADCREDITOS, 1 ESTADO FROM DUAL UNION ALL
  SELECT 5 CURSOID, 'CURSO 5' DESCRIPCION, 6 CANTIDADCREDITOS, 1 ESTADO FROM DUAL
) A;

INSERT INTO UPC_SECCION (SECCIONID, NOMBRE, ESTADO)
SELECT SEQ_UPC_SECCION.NEXTVAL SECCIONID, NOMBRE, ESTADO
FROM
(
  SELECT 1 SECCIONID, 'SECCIÓN A' NOMBRE, 1 ESTADO FROM DUAL UNION ALL
  SELECT 2 SECCIONID, 'SECCIÓN B' NOMBRE, 1 ESTADO FROM DUAL UNION ALL
  SELECT 3 SECCIONID, 'SECCIÓN C' NOMBRE, 1 ESTADO FROM DUAL UNION ALL
  SELECT 4 SECCIONID, 'SECCIÓN D' NOMBRE, 1 ESTADO FROM DUAL
) A;

INSERT INTO UPC_TIPOMATRICULA (TIPOMATRICULAID, NOMBRE)
SELECT TIPOMATRICULAID, NOMBRE
FROM
(
  SELECT 1 TIPOMATRICULAID, 'PRESENCIAL' NOMBRE FROM DUAL UNION ALL
  SELECT 2 TIPOMATRICULAID, 'VIRTUAL' NOMBRE FROM DUAL
) A;

INSERT INTO UPC_SECCIONCURSO (SECCIONID, CURSOID, CANTIDADVACANTES, CANTIDADVACANTESDISPONIBLES, CANTIDADVACANTESUSADAS)
SELECT A.SECCIONID, A.CURSOID, A.CANTIDADVACANTES, A.CANTIDADVACANTESDISPONIBLES, A.CANTIDADVACANTESUSADAS FROM (SELECT S.SECCIONID, C.CURSOID, 3 CANTIDADVACANTES, 3 CANTIDADVACANTESDISPONIBLES, 0 CANTIDADVACANTESUSADAS FROM UPC_SECCION S, UPC_CURSO C WHERE 1 = 1) A LEFT JOIN UPC_SECCIONCURSO B ON A.SECCIONID = B.SECCIONID AND A.CURSOID = B.CURSOID WHERE B.SECCIONID IS NULL;